spring.application.name=ride-management-service
server.port=8083

spring.mongodb.uri=${RIDE_MONGODB_URI}

app.account-service.base-url=${ACCOUNT_SERVICE_BASE_URL:http://localhost:8081}
app.driver-service.base-url=${DRIVER_SERVICE_BASE_URL:http://localhost:8082}

springdoc.swagger-ui.path=/swagger-ui.html