spring.application.name=account-service
spring.mongodb.uri=${SPRING_MONGODB_URI}

server.port=8081

app.jwt.secret-base64=${JWT_SECRET_BASE64}
app.jwt.expiration-ms=3600000

app.bootstrap-admin.email=${ACCOUNT_ADMIN_EMAIL:}
app.bootstrap-admin.password=${ACCOUNT_ADMIN_PASSWORD:}

springdoc.swagger-ui.path=/swagger-ui.html